spring:
  datasource:
    url: jdbc:sqlserver://springboot32.database.windows.net:1433;database=users;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: spring
    password: Rufaid@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9081



