spring:
  datasource:
    url: jdbc:sqlserver://user1534.database.windows.net:1433;database=userdetails;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: User
    password: Use@1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9082







